version: '3.8'

services:
  bdd:
    image: postgres:15
    container_name: voltride_bdd
    environment:
      POSTGRES_DB: voltride
      POSTGRES_USER: voltride
      POSTGRES_PASSWORD: voltride
    ports:
      - "5432:5432"
    volumes:
      - bdd_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: voltride_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: bdd
      ADMINER_DESIGN: nette
    depends_on:
      - bdd

volumes:
  bdd_data: 